# COMMAND: the -f parameter indicates the file to be used as docker-compose.
##############################################################
# docker-compose -f .\docker-compose-server.yml up -d --build #
##############################################################

version: "3.8"

services:
    catalin-trandafir.com_first-web:
        build:
            context: "./main-page"
            dockerfile: "Dockerfile"
        ports:
            - 3001:3001
        environment:
            - NODE_ENV=production
            - DEBUG=nodejs-docker-express:*
            - PORT=3001
            - TZ='Europe/Madrid'
