# COMMAND: the -f parameter indicates the file to be used as docker-compose.
##############################################################
# docker-compose -f .\docker-compose-local.yml up -d --build # 
##############################################################

version: '3.8'

services:
  catalin-trandafir.com:
    build: 
      context: './main-page'
      dockerfile: 'Dockerfile.local'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - DEBUG=nodejs-docker-express:*
      - PORT=3000
      - TZ='Europe/Madrid'
    volumes:
      #PARA QUE FUNCIONE EL NODAEMON
      - ./main-page/src/:/usr/src/app/

      